### ISSUE TITLE
trailing comments should be highlighted

### ISSUE THREAD

**Issue by markhu** [mfukar/robotframework-vim#17]
Currently it seems that only comments with the `#` character in the first column are highlighted as comments.

Comments trailing a command, or on their own indented line are not:

```
 Set Test Message  %{PATH}  # tbd: explain "why"
 # log  something
```

I think they should be.

**Comment by Ferenc-** [comment]
@markhu As of #20 it should more or less work.

**Comment by markhu** [comment]
Awesome, thanks. Verified.
