### ISSUE TITLE
Highlighted predefined keywords are highlighted even if they are only a part of another keyword

### ISSUE THREAD

**Issue by ghost** [mfukar/robotframework-vim#25]
**Library** is a robot setting that is highlighted by the syntax file. Now, if I have the word **Library** anywhere, it is highlighted even if it is not part of the setting. And this is applicable to other words highlighted by the library.

I checked the syntax files. Seems to me, the only way to fix this would be to update the regexes to do some kind of lookahead and lookbehind matching for a non-space character. Are there any other ways that this might be fixed?

I am not that familiar with vimscript.

**Comment by mfukar** [comment]
'Library' is a [keyword](http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html). I'm not sure but it seems you're implying it should not be highlighted in certain places. Is that correct? Could you please provide a testcase?

**Comment by ghost** [comment]
I should have done that in the original issue. Sorry, if my explanation wasn't clear enough.

An example:
```
*** Settings ***
Library    My Test Library

*** Keywords ***
Do Test Setup
    Log    Some Log information

Do Suite Setup
    Log    Some Library information

*** Test Cases ***
Test With Library
    Log    Some Library

Test with Suite Setup and Test Setup
    Do Suite Setup
    Do Test Setup
    Log    La La Suite Setup
    Log    La La Test Setup
```

How it renders:
![screenshot from 2018-02-01 18-36-49](https://user-images.githubusercontent.com/878118/35679967-e4160284-077e-11e8-969c-6c51f7efe5b9.png)

What I think it should do instead:
The syntax highlighting should be based on the context of the words matched.
That is, **Library** should be matched only in the Settings section, and only when it is the name of a setting. Same goes for Test Setup and Suite Setup. They are matched though they appear as substrings in keyword names or as parameters to keywords.
Similarly, **Log** should be matched only when it is a keyword name.
I hope you understand me now. Things are highlighted though they are not supposed to be, in a particular context.

**Comment by mfukar** [comment]
Yeah, I understand what you mean.

However, I don't have enough time to spend on this. Note it is not as simple as you describe, because:

- Matching Robot's 'section' with vim's 'region' is not straightforward
- That doesn't really help; note line 2 of your example, both instances of "Library" are in the section
- For Robot's plain text format, multiple separators are allowed (tab(s), two or more spaces, pipe with spaces, etc)

I'm really disinclined to build a Robot parser in vimscript. :)

**Comment by mfukar** [comment]
That said, if you have time for it I'd gladly accept the PR.
