### ISSUE TITLE
One double quote highlights whole rest of file as string literal

### ISSUE THREAD

**Issue by peritus** [mfukar/robotframework-vim#7]
Given this

```
${string}=  Replace String  ${string}  "  ${EMPTY}
```

(should be `string.replace('"', '')` in python) .. while it is perfectly valid robot framework syntax, the highlighter marks the rest of the file green (in my color scheme). Any idea how to fix that ?

**Comment by markhu** [comment]
I work around this by placing a matching  # "comment to close literal

**Comment by peritus** [comment]
@markhu Yes, that's been my workaround as well. But it's ugly and confuses people who don't use vim.

**Comment by peritus** [comment]
@markhu so this happens for you in the latest version as well (I haven't updated and lost track of this bug) ?
